language: c

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - (cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig)

script:
  - make clean
  - make test
